# Generated by Django 5.0.7 on 2024-08-07 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Nom Inconnu', max_length=100)),
                ('createur', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Nom Inconnu', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='emprunteur',
            name='name',
        ),
        migrations.AddField(
            model_name='emprunteur',
            name='nom',
            field=models.CharField(default='Nom Inconnu', max_length=100),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Titre Inconnu', max_length=100)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('artiste', models.CharField(default='Artiste Inconnu', max_length=100)),
                ('emprunteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaires.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Titre Inconnu', max_length=100)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('realisateur', models.CharField(default='Réalisateur Inconnu', max_length=100)),
                ('emprunteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaires.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Titre Inconnu', max_length=100)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('auteur', models.CharField(default='Auteur Inconnu', max_length=100)),
                ('emprunteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaires.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('cd_emprunte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaires.cd')),
                ('dvd_emprunte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaires.dvd')),
                ('livre_emprunte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaires.livre')),
                ('membre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaires.membre')),
            ],
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
